export const ADD_ITEM_TO_WISHLIST = "ADD_ITEM_TO_WISHLIST";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_WISHLIST = "REMOVE_ITEM_FROM_WISHLIST";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
